### PR TITLE
First demo video

### PR DESCRIPTION
**Pull request by clement-moulin-frier**
## Description
@corentinlger @Marsolo1 Please check and see if you could make the readme more appealing with vid or gif

### CODE REVIEW

**Comment by corentinlger** [comment]
I'm not a huge fan of the Readme render at the moment, but did you imagine something like that @clement-moulin-frier ?

**Comment by clement-moulin-frier** [comment]
The ideal would be to have a gif of the entire screen of the youtube video, starting at 8s. Is it possible or is it too long for a GIF? If too long, please let me know what is the maximum duration we could have. Thanks

**Comment by Marsolo1** [comment]
I think that a gif shouldn't last more than a few seconds. Maybe we could have the same gif as the current one but with the whole screen instead of just the plot, and a bigger link to the video below?

**Comment by clement-moulin-frier** [comment]
Sounds good to me, let's have a short gif where we see the interaction with the interface, e.g. from 1:00 to 1:15 in the full vid (or recording a new short vid just for this purpose). Making the link to the video more visible is a good idea

**Comment by Marsolo1** [comment]
I made a gif with the full screen, including config modifications and a start so we see the entities moving

**Comment by Marsolo1** [comment]
@clement-moulin-frier you can tell me what you think, if I should change it or not

**Comment by clement-moulin-frier** [comment]
It works for me @Marsolo1 , you can merge it. Thanks

**Pull request merged**
